"""
Reproduction of Fig. 2 of Geremia, Stockton, Doherty & Mabuchi,
"Quantum Kalman Filtering and the Heisenberg Limit in Atomic Magnetometry"
(quant-ph/0306192).

We compare two estimators of a static magnetic field B from the continuous
QND measurement record of an atomic spin ensemble:

  1. The quantum Kalman filter (QKF), Eq. (9) of the paper, with gain
     G = D^{-2} (Bvec + V C^T) computed from the Riccati equation, Eq. (11).
  2. Simple linear regression of the photocurrent: B_reg = slope/(gamma*J).

System model (Gaussian conditional dynamics, Eqs. 4-5, with the truth
generated by the same stochastic model the filter assumes):

    d<Jz>_c   = gamma*B*J*exp(-M*t/2) dt + 2*sqrt(M*eta)*Vq(t) dW
    Vq(t)      = (J/2) / (1 + 2*M*eta*J*t)          [solution of Eq. 5]
    dXi        = <Jz>_c dt + D dW ,   D = 1/(2*sqrt(M*eta))   [Eq. 2, rescaled]

Kalman filter for the state x = (Jz, B):

    A(t) = [[0, gamma*J*exp(-M*t/2)], [0, 0]],  Bvec = (Vq(t), 0)^T,
    C = (1, 0),  D = 1/(2*sqrt(M*eta))

    dx_hat = A x_hat dt + K(t) (dXi - C x_hat dt),
    K(t)   = D^{-2} (Bvec + V C^T)

NOTE ON EQ. (11): the process noise on Jz (quantum diffusion 2*sqrt(M*eta)*Vq dW)
is PERFECTLY CORRELATED with the measurement noise D dW -- it is the same Wiener
process. The standard Kalman-Bucy equations with correlated noise then give

    Vdot = Abar V + V Abar^T  -  D^{-2} V C^T C V ,
    Abar = A - D^{-2} Bvec C

i.e. the quadratic term enters with a MINUS sign (the printed Eq. 11 appears to
contain a sign typo: with a plus sign the covariance would not decrease). The
GG^T process-noise term cancels exactly against the gain-correlation term
because G = Bvec/D. We verify the minus-sign Riccati equation against the
analytic solution Eq. (12) below.

UNITS: the parameter set quoted in the paper (M = 100 kHz, J = 4e6,
gamma = 1 kHz/mG) does not self-consistently reproduce the numerical axis
values printed in Fig. 2, so we work in arbitrary units (M = gamma = eta = 1)
with J = 100 for the Monte-Carlo main panel. All the physics of the figure --
the prior-limited start, the convergence of regression to the QKF for
t >> (J*M)^{-1}, the t^{-3} dependence and the 1/J (Heisenberg) scaling in the
inset -- is reproduced faithfully.

Outputs:
    fig2_reproduction.png
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

rng = np.random.default_rng(11)

# ----------------------------------------------------------------------
# Global parameters (arbitrary units)
# ----------------------------------------------------------------------
M     = 1.0      # measurement strength
eta   = 1.0      # detector efficiency
gamma = 1.0      # gyromagnetic ratio
B_true = 1.0     # applied field

D  = 1.0 / (2.0 * np.sqrt(M * eta))   # measurement noise level of dXi
g  = 1.0 / D**2                       # = 4*M*eta, appears in gain & Riccati


def Vq(t, J):
    """Conditional quantum variance <dJz^2>(t), solution of Eq. (5)."""
    return (J / 2.0) / (1.0 + 2.0 * M * eta * J * t)


def f_larmor(t, J):
    """Time-dependent coupling gamma*J*exp(-M t/2) in the A matrix."""
    return gamma * J * np.exp(-M * t / 2.0)


# ----------------------------------------------------------------------
# Riccati equation, Eq. (11) with corrected (minus) sign
# ----------------------------------------------------------------------
def riccati(J, prior_B2, t_grid):
    """
    Integrate the estimator covariance V(t) = [[V11, V12], [V12, V22]]
    and return (V11, V12, V22) evaluated on t_grid.

    V11 = dJz_tilde^2 (error of the Jz estimate),
    V22 = dB_tilde^2  (error of the field estimate),
    initial conditions V11(0) = V12(0) = 0, V22(0) = prior_B2.
    """
    def rhs(t, v):
        V11, V12, V22 = v
        vq = Vq(t, J)
        f = f_larmor(t, J)
        dV11 = 2.0 * (-g * vq * V11 + f * V12) - g * V11**2
        dV12 = -g * vq * V12 + f * V22 - g * V11 * V12
        dV22 = -g * V12**2
        return [dV11, dV12, dV22]

    sol = solve_ivp(rhs, (0.0, t_grid[-1]), [0.0, 0.0, prior_B2],
                    method="LSODA", t_eval=t_grid, rtol=1e-10, atol=1e-12)
    return sol.y[0], sol.y[1], sol.y[2]


# ----------------------------------------------------------------------
# Analytic infinite-prior solution, Eq. (12)  [eta = 1]
# ----------------------------------------------------------------------
def dB2_eq12(J, t):
    """
    Field-estimation variance dB^2(t) for dB^2(0) -> infinity, Eq. (12).
    Rewritten in a numerically stable form: the printed expression suffers
    catastrophic cancellation for M*t << 1 (terms of order J cancel down to
    order J*(M*t)^4).  With u = exp(-M*t/2), w = 1 - u, the denominator is

        denom = 2*J*w*[eps*(2 - w) - 4*w] + (eps - 2*w - w**2),  eps = M*t

    which is algebraically identical to a*exp(-M t) + 4*exp(-M t/2)*(4J+1) + b.
    """
    eps = M * np.asarray(t, dtype=float)
    w = -np.expm1(-eps / 2.0)                  # 1 - exp(-eps/2), accurate
    denom = 2.0 * J * w * (eps * (2.0 - w) - 4.0 * w) + (eps - 2.0 * w - w**2)
    num = 1.0 + 2.0 * eta * J * M * eps / M    # = 1 + 2*eta*J*M*t
    return (M / (4.0 * gamma * J))**2 * num / denom


# ----------------------------------------------------------------------
# Monte-Carlo: truth + QKF + running linear regression (vectorized)
# ----------------------------------------------------------------------
def run_ensemble(J, prior_B2, t_max, n_steps, n_traj, sample_idx, rng,
                 B_vals=None):
    """
    Simulate n_traj trajectories of the conditional dynamics, run the QKF
    and a cumulative linear regression on each, and return the empirical
    estimation errors E[(B_est - B)^2] at the time indices `sample_idx`.

    B_vals: true field per trajectory. If None, each trajectory's B is drawn
    from the prior N(0, prior_B2), so the empirical QKF error is a consistent
    Bayesian test of the Riccati variance V22(t). (The paper instead fixes
    B = 1; for a linear estimator the regression error is unaffected, but the
    early-time QKF error then equals B^2 rather than the prior variance.)

    The "linear regression" estimator fits the photocurrent samples to
    c0 + B * phi(t) with the known deterministic signal shape
    phi(t) = gamma*J*(2/M)*(1 - exp(-M t/2)), i.e. the integral of the Larmor
    drift in Eq. (4). For M*t << 1 this reduces to fitting a straight line of
    slope gamma*J*B, but it avoids the O(M*t) bias of a pure slope fit once
    the Bloch-vector decay is no longer negligible.
    """
    dt = t_max / n_steps
    t_grid = np.arange(n_steps + 1) * dt

    if B_vals is None:
        B_vals = rng.normal(0.0, np.sqrt(prior_B2), size=n_traj)
    B_vals = np.broadcast_to(np.asarray(B_vals, dtype=float), (n_traj,))

    # deterministic Kalman gain from the Riccati solution
    V11, V12, V22 = riccati(J, prior_B2, t_grid)
    K1 = g * (Vq(t_grid, J) + V11)     # gain on the Jz estimate
    K2 = g * V12                       # gain on the B estimate

    # state arrays over the ensemble
    Jz   = np.zeros(n_traj)            # true conditional <Jz>_c
    Jz_h = np.zeros(n_traj)            # QKF estimate of Jz
    B_h  = np.zeros(n_traj)            # QKF estimate of B (prior mean 0)

    # running sums for cumulative regression of z_k = dXi_k/dt on phi(t_k),
    # phi(t) = gamma*J*(2/M)*(1 - exp(-M t/2))  (Larmor signal shape per unit B)
    Sp = 0.0; Spp = 0.0                # scalars (same times for all traj)
    Sz  = np.zeros(n_traj)
    Spz = np.zeros(n_traj)

    err_kf  = np.full(len(sample_idx), np.nan)
    err_reg = np.full(len(sample_idx), np.nan)
    sample_set = {k: i for i, k in enumerate(sample_idx)}

    sq_dt = np.sqrt(dt)
    for k in range(n_steps):
        tk = t_grid[k]
        vq = Vq(tk, J)
        f  = f_larmor(tk, J)

        dW = rng.normal(0.0, sq_dt, size=n_traj)
        dXi = Jz * dt + D * dW                          # measurement record

        # --- truth update (Eq. 4, with analytic Vq from Eq. 5) ---
        Jz = Jz + gamma * B_vals * J * np.exp(-M * tk / 2.0) * dt \
                + 2.0 * np.sqrt(M * eta) * vq * dW

        # --- Kalman filter update (Eq. 9) ---
        innov = dXi - Jz_h * dt
        Jz_h = Jz_h + f * B_h * dt + K1[k] * innov
        B_h  = B_h + K2[k] * innov

        # --- cumulative linear regression on photocurrent samples ---
        z = dXi / dt
        phi = gamma * J * (2.0 / M) * (-np.expm1(-M * tk / 2.0))
        Sp += phi; Spp += phi * phi
        Sz += z;   Spz += phi * z
        n = k + 1

        if k in sample_set and n >= 10:
            i = sample_set[k]
            err_kf[i] = np.mean((B_h - B_vals)**2)
            det = n * Spp - Sp * Sp
            B_reg = (n * Spz - Sp * Sz) / det          # coefficient of phi(t)
            err_reg[i] = np.mean((B_reg - B_vals)**2)

    return t_grid, err_kf, err_reg, V22


# ======================================================================
# Sanity check: corrected Riccati equation vs analytic Eq. (12)
# ======================================================================
J_chk = 100.0
t_chk = np.linspace(5e-4, 0.05, 40)
_, _, V22_chk = riccati(J_chk, 1e12, t_chk)         # huge prior ~ infinity
rel = np.abs(V22_chk / dB2_eq12(J_chk, t_chk) - 1.0)
print(f"Riccati (minus sign) vs Eq. (12), J=100, infinite prior: "
      f"max relative deviation = {rel.max():.2e}")

# ======================================================================
# Main panel: J = 100, prior dB^2(0) = 100, scaled time JMt in [0, 5]
# ======================================================================
J_main   = 100.0
prior    = 100.0
s_max    = 5.0
t_max    = s_max / (J_main * M)
n_steps  = 5000
n_traj   = 2000

sample_idx = np.unique(np.linspace(50, n_steps - 1, 40).astype(int))
t_grid, err_kf, err_reg, V22_prior = run_ensemble(
    J_main, prior, t_max, n_steps, n_traj, sample_idx, rng)
s_grid = J_main * M * t_grid
s_samp = s_grid[sample_idx]

fig, ax = plt.subplots(figsize=(7.2, 5.4))

ax.plot(s_grid, np.log10(V22_prior), "b-", lw=1.5,
        label=rf"QKF theory, Riccati Eq. (11), $\Delta\tilde B^2(0)={prior:.0f}$")
mask = s_grid > 0.02
ax.plot(s_grid[mask], np.log10(dB2_eq12(J_main, t_grid[mask])), "k--", lw=1.2,
        label=r"analytic Eq. (12), $\Delta\tilde B^2(0)\to\infty$")
ax.plot(s_samp, np.log10(err_kf), "bx", ms=6, mew=1.5,
        label=rf"QKF Monte Carlo ({n_traj} traj.)")
ax.plot(s_samp, np.log10(err_reg), "o", ms=6, mfc="none", mec="darkorange",
        mew=1.5, label="linear regression Monte Carlo")

ax.set_xlabel(r"Scaled time, $JMt$")
ax.set_ylabel(r"Estimation error, $\log_{10}[\Delta\tilde B^2(t)]$ (arb. units)")
ax.set_xlim(0, s_max)
ax.set_ylim(-0.5, 7)
ax.legend(loc="upper right", fontsize=9)
ax.set_title(rf"QKF vs linear regression  ($J={J_main:.0f}$, $M=\gamma=\eta=1$, "
             rf"$B\sim\mathcal{{N}}(0,{prior:.0f})$ per trajectory)")

# ======================================================================
# Inset: Heisenberg (1/J) scaling of the detection threshold
# ======================================================================
axin = ax.inset_axes([0.40, 0.30, 0.42, 0.40])

J_list = [1e3, 1e4, 1e5, 1e6]
t_inset = np.logspace(-3, -1, 100)
for Jv in J_list:
    axin.plot(np.log10(M * t_inset), np.log10(np.sqrt(dB2_eq12(Jv, t_inset))),
              "-", lw=1.0, color="navy")
    axin.text(-1.0 + 0.06, np.log10(np.sqrt(dB2_eq12(Jv, 0.1))) + 0.12,
              rf"$J=10^{{{int(np.log10(Jv))}}}$", fontsize=7, color="navy")

# Monte-Carlo points on the inset for the two smallest ensembles
prior_inset = 1e4
for Jv, mark in [(1e3, "x"), (1e4, "x")]:
    n_st = 40000
    t_mx = 0.1
    samp = np.unique((np.geomspace(2e-3, 0.1, 7) / (t_mx / n_st)).astype(int)) - 1
    tg, e_kf, e_reg, _ = run_ensemble(Jv, prior_inset, t_mx, n_st, 400, samp,
                                      rng, B_vals=B_true)
    axin.plot(np.log10(M * tg[samp]), 0.5 * np.log10(e_kf), "rx", ms=4, mew=1.2)
    axin.plot(np.log10(M * tg[samp]), 0.5 * np.log10(e_reg), "o", ms=4,
              mfc="none", mec="darkorange", mew=1.0)

axin.set_xlabel(r"$\log_{10}(Mt)$", fontsize=8)
axin.set_ylabel(r"$\log_{10}[\delta\tilde B(t)]$", fontsize=8)
axin.tick_params(labelsize=7)
axin.set_title(r"$\delta\tilde B\propto 1/J$ (Heisenberg scaling)", fontsize=8)

fig.tight_layout()
fig.savefig("fig2_reproduction.png", dpi=200, bbox_inches="tight")
#plt.close(fig)
plt.show()
# final numerical checks
i_last = -1
print(f"main panel at JMt = {s_samp[i_last]:.2f}:  "
      f"MC QKF error = {err_kf[i_last]:.3f},  Riccati prediction = "
      f"{V22_prior[sample_idx[i_last]]:.3f}")
print(f"                         MC regression error = {err_reg[i_last]:.3f},  "
      f"Eq. (13) asymptote 3M^2 J/(gamma^2 s^3) = "
      f"{3*M**2*J_main/(gamma**2*s_samp[i_last]**3):.3f}")
print("Saved fig2_reproduction.png")
